alarm-redist/fifty-states

analyses/TN_cd_2020/01_prep_TN_cd_2020.R, analyses/TN_cd_2020/02_setup_TN_cd_2020.R, analyses/TN_cd_2020/03_sim_TN_cd_2020.R, analyses/TN_cd_2020/doc_TN_cd_2020.md
In Tennessee, there are no rules for redistricting Congressional districts ([NCSL](https://www.ncsl.org/research/redistricting/redistricting-criteria.aspx)).
Although there are no rules, in practice, the state does avoid splitting its boundaries. The 2010 map split 8 of its 95 counties, and split only 4 of the 228 municipalities that comes with our default tigris call, and only 2 of the 20 largest municipalities. That said, the 2020 split the city of Nashville, splitting its county into three CDs, showing that these practices are not set in stone.
Therefore, to enforce some county splitting avoidance, we took 20 largest cities in Tennessee (each with a population of at least 40,000) and concatenated them with counties so that these "pseudo-counties" were smaller units of geography that …
=> 2020 Tennessee Congressional Districts

analyses/TN_cd_2020/01_prep_TN_cd_2020.R, analyses/WA_cd_2020/01_prep_WA_cd_2020.R, analyses/WA_cd_2020/02_setup_WA_cd_2020.R, analyses/WA_cd_2020/03_sim_WA_cd_2020.R, analyses/WA_cd_2020/doc_WA_cd_2020.md
In Washington, districts must, under [Article 2, Section 43 of the constitution](https://leg.wa.gov/CodeReviser/Pages/WAConstitution.aspx) and [RCW 44.05.090](https://apps.leg.wa.gov/RCW/default.aspx?cite=44.05.090):
1. not be connected across geographic barriers, although ferries across water may establish contiguity 
1. "provide fair and effective representation and ... encourage electoral competition"
To reflect the barriers and contiguity requirements, we remove edges across water regions and mountains in the adjacency graph, but …
=> 2020 Washington Congressional Districts

analyses/KS_cd_2020/01_prep_KS_cd_2020.R, analyses/KS_cd_2020/02_setup_KS_cd_2020.R, analyses/KS_cd_2020/03_sim_KS_cd_2020.R, analyses/KS_cd_2020/doc_KS_cd_2020.md
In Kansas, according to the [Proposed Guidelines and Criteria for 2022 Kansas Congressional Redistricting](https://redistricting.lls.edu/wp-content/uploads/KS-Proposed-redistricting-guidelines.pdf) districts must:
5. preserve the cores of existing districts
6. preserve communities of social, cultural, racial, ethnic, and economic interest to the extent possible
We enforce a maximum population deviation of 0.5%. We add a county constraint.
Data for Kansas comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/). Data for the 2022 Kansas enacted congressional map comes from the [American …
=> 2020 Kansas Congressional Districts

analyses/CT_cd_2020/01_prep_CT_cd_2020.R, analyses/CT_cd_2020/02_setup_CT_cd_2020.R, analyses/CT_cd_2020/03_sim_CT_cd_2020.R, analyses/CT_cd_2020/doc_CT_cd_2020.md
In Connecticut, there are no state law requirements for congressional districts
We enforce a maximum population deviation of 0.5%, which is in line with the low population deviation observed in the 2000 and 2010 congressional district plans.
Data for Connecticut comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Connecticut.
@christopherkenny
=> 2020 Connecticut Congressional Districts

analyses/PA_cd_2020/01_prep_PA_cd_2020.R, analyses/PA_cd_2020/02_setup_PA_cd_2020.R, analyses/PA_cd_2020/03_sim_PA_cd_2020.R, analyses/PA_cd_2020/doc_PA_cd_2020.md
In Pennsylvania, there are few formal districting requirements, but districts must generally:
Data for Pennsylvania comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Pennsylvania.
To balance county and municipality splits, we create pseudocounties for use in
the county constraint. These are counties, outside of Allegheny County,
Montgomery County, and Philadelphia County. Within …
=> 2020 Pennsylvania Congressional Districts

analyses/NC_cd_2020/01_prep_NC_cd_2020.R, analyses/NC_cd_2020/doc_NC_cd_2020.md
Swapped out reference plan in 2020 North Carolina congressional redistricting simulations with the remedial map imposed on 2/23/2022. Data for the remedial plan comes from the [North Carolina General Assembly](https://www.ncleg.gov/Redistricting).
Updated validation plot:
@CoryMcCartan
=> NC remedial map update

analyses/GA_cd_2020/01_prep_GA_cd_2020.R, analyses/GA_cd_2020/02_setup_GA_cd_2020.R, analyses/GA_cd_2020/03_sim_GA_cd_2020.R, analyses/GA_cd_2020/doc_GA_cd_2020.md
In Georgia, districts must, under the 2021-22 State House and Senate Reapportionment Committee guidelines:
5. "efforts should be made to avoid the unnecessary pairing of incumbents"
Data for Georgia comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Georgia.
To balance county and municipality splits, we create pseudocounties for use in the county constraint, which leads to fewer municipality splits than using a county constraint.
We apply a …
=> 2020 Georgia Congressional Districts

analyses/WI_cd_2020/01_prep_WI_cd_2020.R, analyses/WI_cd_2020/02_setup_WI_cd_2020.R, analyses/WI_cd_2020/03_sim_WI_cd_2020.R, analyses/WI_cd_2020/doc_WI_cd_2020.md
In Wisconsin, districts must:
We add a county/municipality constraint as described below.
Data for Wisconsin comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Wisconsin.
We create pseudocounties for use in the county constraint to match norms in the state of having low county and municipality splits, despite no rules regarding this. Municipality lines are used within Milwukee County, which is larger than a congressional district in population.
@CoryMcCartan
=> 2020 Wisconsin Congressional Districts

analyses/RI_cd_2020/03_sim_RI_cd_2020.R, analyses/RI_cd_2020/doc_RI_cd_2020.md
In Rhode Island, according to the [Rhode Island Laws, Chapter 100, Section 2](http://webserver.rilin.state.ri.us/PublicLaws/law11/law11100.htm) districts must:
4. preserve state senate district boundaries as much as possible
We add a VRA constraint targeting one minority opportunity district.
Data for Rhode Island comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/). Data for the 2022 Rhode Island enacted congressional map comes from the [American Redistricting Project](https://thearp.org/state/rhode-island/).
We sample 4,000 districting plans for …
=> Re-run 2020 Rhode Island Congressional Districts

R/template/03_sim.R, analyses/OR_cd_2020/01_prep_OR_cd_2020.R, analyses/OR_cd_2020/03_sim_OR_cd_2020.R, analyses/OR_cd_2020/doc_OR_cd_2020.md, fifty-states.Rproj
In Oregon, districts must, under Or. Rev. Stat. § 188.010:
1. be of equal population
1. utilize existing geographic or political boundaries
1. not divide communities of common interest
1. be connected by transportation links
Additionally, districts may not favor any political party or incumbent, and may not dilute the voting strength of any language or ethnic minority group.
To reflect the transportation links constraint, we remove edges in the adjacency graph for counties not connected by a state or federal highway.
Data for Oregon comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/). …
=> Re-run 2020 Oregon Congressional Districts

analyses/IA_cd_2020/03_sim_IA_cd_2020.R, analyses/IA_cd_2020/doc_IA_cd_2020.md
In Iowa, districts must:
1. be constructed only from counties
1. be geographically compact, as defined by two compactness measures:
1. length-width compactness, which measures the total absolute difference between the length and width of a district, across all districts
1. perimeter compactness, which measures the total perimeter of all districts
We enforce a maximum population deviation of 0.01%, given strict historical deviation standards.
We also merge VTDs into counties and run the simulation at the county level.
For compactness, we increase the `compactness` parameter to 1.1, which does not create too much inefficiency.
Data for Iowa comes from the ALARM Project's [2020 Redistricting Data …
=> Re-run 2020 Iowa Congressional Districts

R/template/dataverse_addendum.md, analyses/MI_cd_2020/02_setup_MI_cd_2020.R, analyses/MI_cd_2020/03_sim_MI_cd_2020.R, analyses/MI_cd_2020/doc_MI_cd_2020.md
In Michigan, districts must:
1. be contiguous (Mich. Const. art. IV, § 6(13)(b)). Island areas are considered to be contiguous by land to the county of which they are a part.
1. have equal populations (Mich. Const. art. IV, § 6(13)(a))
1. be geographically compact (Mich. Const. art. IV, § 6(13)(g))
1. reflect consideration of county, city, and township boundaries (Mich. Const. art. IV, § 6(13)(f))
1. not provide a disproportionate advantage to any political party, determined using accepted measures of partisan fairness (Mich. Const. art. IV, § 6(13)(d))
Based on the current plan, two districts should be majority-minority in order to comply with the Voting Rights Act.
We apply a county/municipality constraint, as described below. 
We …
=> Re-run 2020 Michigan Congressional Districts

analyses/AZ_cd_2020/03_sim_AZ_cd_2020.R, analyses/AZ_cd_2020/doc_AZ_cd_2020.md, fifty-states.Rproj
In Arizona, districts must, [under the state constitution](https://www.azleg.gov/viewDocument/?docName=http://www.azleg.gov/const/4/1.p2.htm):
1. favor competitive districts to the extent practicable
We add a county/municipality constraint, as described below.
We add a VRA constraint targeting two majority-HVAP districts which are also substantially majority-minority.
Not every plans is guaranteed to have two majority-HVAP districts, however.
Data for Arizona comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
No manual …
=> Re-run 2020 Arizona Congressional Districts

analyses/WA_cd_2020/03_sim_WA_cd_2020.R, analyses/WA_cd_2020/doc_WA_cd_2020.md
In Washington, districts must, under [Article 2, Section 43 of the constitution](https://leg.wa.gov/CodeReviser/Pages/WAConstitution.aspx) and [RCW 44.05.090](https://apps.leg.wa.gov/RCW/default.aspx?cite=44.05.090):
1. not be connected across geographic barriers, although ferries across water may establish contiguity 
1. "provide fair and effective representation and ... encourage electoral competition"
To reflect the barriers and contiguity requirements, we remove edges across water regions and mountains in the adjacency graph, but …
=> Re-run 2020 Washington Congressional Districts

DESCRIPTION, analyses/MS_cd_2020/01_prep_MS_cd_2020.R, analyses/MS_cd_2020/03_sim_MS_cd_2020.R, analyses/MS_cd_2020/doc_MS_cd_2020.md, fifty-states.Rproj
In Mississippi, [under Mississippi Code 5-3-123](https://advance.lexis.com/documentpage/?pdmfid=1000516&crid=d062935b-fafc-45ea-a1f4-dc1ba2a3377c&nodeid=AAEAACAAFAAC&nodepath=%2FROOT%2FAAE%2FAAEAAC%2FAAEAACAAF%2FAAEAACAAFAAC&level=4&haschildren=&populated=false&title=%C2%A7+5-3-123.+Preparation+of+plan+to+redistrict+congressional+districts.&config=00JABhZDIzMTViZS04NjcxLTQ1MDItOTllOS03MDg0ZTQxYzU4ZTQKAFBvZENhdGFsb2f8inKxYiqNVSihJeNKRlUp&pddocfullpath=%2Fshared%2Fdocument%2Fstatutes-legislation%2Furn%3AcontentItem%3A8P6B-7XD2-8T6X-701X-00008-00&ecomp=_g1_kkk&prid=4f3abbc9-f98b-4883-a5ce-fcb4020b7438) and [Committee agreement](https://www.dropbox.com/s/z36sc17c3m1cewv/MississippiLegislativeAndCongressionalRedistrictingCommitteeMinutes2012-04-05.pdf), districts must:
1. have …
=> Re-run 2020 Mississippi Congressional Districts

analyses/MT_cd_2020/03_sim_MT_cd_2020.R, analyses/MT_cd_2020/doc_MT_cd_2020.md
In Montana, districts must:
Data for Montana comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Montana across two runs of the SMC algorithm.
To balance county and municipality splits, we create pseudocounties for use in the county constraint.
These are counties for all counties with a population under 50,000.
Within counties larger than 50,000, municipalities are each their own …
=> Re-run 2020 Montana Congressional Districts

analyses/NE_cd_2020/02_setup_NE_cd_2020.R, analyses/NE_cd_2020/03_sim_NE_cd_2020.R, analyses/NE_cd_2020/doc_NE_cd_2020.md
In Nebraska, districts must, under a [legislative resolution](https://nebraskalegislature.gov/FloorDocs/107/PDF/Intro/LR134.pdf):
1. have equal populations (specifically, within 0.5% of equality)
1. preserve the cores of prior districts
1. not be drawn using partisan information
We apply a county constraint.
We preprocess the map to ensure the cores of prior districts are preserved, as described below.
Data for Nebraska comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
To preserve the cores of prior districts, we merge all precincts which are more than …
=> Re-run 2020 Nebraska Congressional Districts

analyses/WV_cd_2020/01_prep_WV_cd_2020.R, analyses/WV_cd_2020/03_sim_WV_cd_2020.R, analyses/WV_cd_2020/doc_WV_cd_2020.md
[In West Virginia, under the state constitution, districts must](http://www.wvlegislature.gov/WVCODE/WV_CON.cfm):
1. be contiguous (I 1-4)
1. have equal populations (I 1-4)
1. be geographically compact (I 1-4)
1. districts must be made of contiguous counties (I 1-4)
We simulate at the county level.
Data for West Virginia comes from the [The Upshot Presidential Precinct Map data](https://github.com/TheUpshot/presidential-precinct-map-2020) and are joined with county level Census data.
Data is aggregated to the county level.
We sample 5,000 districting plans for West Virginia, across 4 independent runs of the SMC algorithm.
```
SMC: 5,000 sampled plans of 2 districts on 55 units …
```
=> Re-run 2020 West Virginia Congressional Districts

analyses/ID_cd_2020/01_prep_ID_cd_2020.R, analyses/ID_cd_2020/03_sim_ID_cd_2020.R, analyses/ID_cd_2020/doc_ID_cd_2020.md
[In Idaho, districts must](https://legislature.idaho.gov/statutesrules/idstat/Title72/T72CH15/SECT72-1506/):
1. be contiguous (72-1506(6)).
1. have equal populations (72-1506(3)).
1. be geographically compact (72-1506(4), 72-1506(5)).
1. preserve county and municipality boundaries as much as possible (72-1506(2)).
1. not be drawn to favor party or incumbents (72-1506(8)).
1. connect counties based on highways (72-1506(9)).
Data for Idaho comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
Borders between counties which are not connected by highways were removed.
We sample 5,000 districting plans for Idaho, across 2 independent runs of the SMC algorithm.
We sample …
=> Re-run 2020 Idaho Congressional Districts

analyses/ME_cd_2020/01_prep_ME_cd_2020.R, analyses/ME_cd_2020/03_sim_ME_cd_2020.R, analyses/ME_cd_2020/doc_ME_cd_2020.md
[In Maine, following Title 21-A, Chapter 15, Section 1206, districts must](https://legislature.maine.gov/legis/statutes/21-A/title21-Asec1206.html):
1. be contiguous (1)
1. have equal populations (1)
1. be geographically compact (1)
1. preserve county and municipality boundaries as much as possible (1)
We apply the standard algorithmic county constraint.
Data for Maine comes from the [Voting and Election Science Team](https://dataverse.harvard.edu/dataverse/electionscience) for 2016, 2018, and 2020. It is retabulated to 2020 Census tracts, as 2020 Census VTDs do not cover the majority of Maine's geography.
Islands tracts were connected to the nearest tract within the same district.
We sample 5,000 districting plans for Maine, across 4 …
=> Re-run 2020 Maine Congressional Districts

analyses/PA_cd_2020/03_sim_PA_cd_2020.R, analyses/PA_cd_2020/doc_PA_cd_2020.md
In Pennsylvania, there are few formal districting requirements, but districts must generally:
Data for Pennsylvania comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 10,000 districting plans for Pennsylvania across two runs of the SMC algorithm, then filter down to 5,000 total plans.
To balance county and municipality splits, we create pseudocounties for use in
the county constraint. These are counties, …
=> Re-run 2020 Pennsylvania Congressional Districts

analyses/NV_cd_2020/01_prep_NV_cd_2020.R, analyses/NV_cd_2020/03_sim_NV_cd_2020.R, analyses/NV_cd_2020/doc_NV_cd_2020.md
In Nevada, districts must:
1. preserve communities of interest.
We use a county constraint to avoid splitting counties, municipalities, and potential COIs.
Data for Nevada comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Nevada across 2 independent runs of the SMC algorithm.
We use a standard algorithmic county constraint.
```
SMC: 5,000 sampled plans of 4 districts on 2,102 units
`est_label_mult`=1 …
```
=> Re-run 2020 Nevada Congressional Districts

analyses/OH_cd_2020/01_prep_OH_cd_2020.R, analyses/OH_cd_2020/03_sim_OH_cd_2020.R, analyses/OH_cd_2020/doc_OH_cd_2020.md
In Ohio, districts must, under [Article XIX of the Ohio Constitution](https://www.legislature.ohio.gov/laws/ohio-constitution/article?id=19):
1. not split Cincinnati or Cleveland
1. minimize splitting of Columbus
1. split no more than 18 counties once, and no more than 5 counties twice, and no counties three times
1. additionally preserve county and municipality boundaries where possible
We employ a variety of anti-split constraints, both in pre-processing and in simulation, as detailed below.
Ohio also has one VRA district in Cuyahoga county.
Data for Ohio comes from the ALARM Project's [2020 Redistricting Data …
=> Re-run 2020 Ohio Congressional Districts

analyses/OK_cd_2020/01_prep_OK_cd_2020.R, analyses/OK_cd_2020/03_sim_OK_cd_2020.R, analyses/OK_cd_2020/doc_OK_cd_2020.md
[In Oklahoma, districts must](https://oksenate.gov/sites/default/files/inline-files/Senate%20Redistricting%20Guidelines.pdf):
1. be contiguous (C)
1. have equal populations (A.2)
1. be geographically compact (C)
1. preserve county and municipality boundaries as much as possible (C)
Data for Oklahoma comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Oklahoma across 2 independent runs of the SMC algorithm.
We use a pseudo county constraint which uses counties, except for Oklahoma County which uses municipalities.
No …
=> Re-run 2020 Oklahoma Congressional Districts

analyses/IN_cd_2020/01_prep_IN_cd_2020.R, analyses/IN_cd_2020/03_sim_IN_cd_2020.R, analyses/IN_cd_2020/doc_IN_cd_2020.md
In Indiana, districts must:
Data for Indiana comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Indiana across 2 independent runs of the SMC algorithm.
We use counties, despite the lack of requirements, as the enacted does generally follow county lines.
```
SMC: 5,000 sampled plans of 9 districts on 5,159 units
Plan diversity 80% range: 0.64 to 0.86
R-hat values for summary statistics:
pop_overlap …
```
=> Re-run 2020 Indiana Congressional Districts

analyses/MD_cd_2020/01_prep_MD_cd_2020.R, analyses/MD_cd_2020/03_sim_MD_cd_2020.R, analyses/MD_cd_2020/doc_MD_cd_2020.md
[In Maryland, districts must](https://governor.maryland.gov/wp-content/uploads/2021/01/execorder.pdf):
1. be contiguous (C.1.a.i.)
1. have equal populations (C.1.c.i.)
1. be geographically compact (C.1.a.iv.)
1. preserve county and municipality boundaries as much as possible (C.1.a.iii.)
1. not consider incumbent or partisan information (C.1.b.i., C.1.b.ii.)
Data for Maryland comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Maryland across 2 independent runs of the SMC algorithm.
```
SMC: 5,000 sampled plans of 8 …
```
=> Re-run 2020 Maryland Congressional Districts

analyses/AR_cd_2020/03_sim_AR_cd_2020.R, analyses/AR_cd_2020/doc_AR_cd_2020.md
In Arkansas, there are no state law requirements for congressional districts.
We enforce a maximum population deviation of 0.5%, which is in line with the low deviation seen in past congressional district maps.
We limit the number of county/municipality splits, which is in line with the small number of county/municipality splits observed in past congressional district maps.
Data for Arkansas comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
Data for Arkansas' 2020 congressional district map comes from All About Redistricting's [Maps for Download](https://redistricting.lls.edu/mapdownload/).
We sample 5,000 districting plans for Arkansas across two independent runs …
=> Re-run 2020 Arkansas Congressional Districts

analyses/NM_cd_2020/02_setup_NM_cd_2020.R, analyses/NM_cd_2020/03_sim_NM_cd_2020.R, analyses/NM_cd_2020/doc_NM_cd_2020.md
In New Mexico, districts must, under [legislation code SB 304](https://www.nmlegis.gov/Legislation/Legislation?Chamber=S&LegType=B&LegNo=304&year=21):
2. be reasonably compact
3. be as equal in population as practicable
4. to the extent feasible, preserve communities of interest and take into consideration political and geographic boundaries
5. to the extent feasible, preserve the core of existing districts
Additionally, race-neutral districting principles shall not be subordinated to racial considerations
We constrain the number of county divisions to 1 less than the number of Congressional Districts.
We perform cores-based simulations, thereby preserving cores of prior districts.
Data for New Mexico comes from the ALARM …
=> Re-run 2020 New Mexico Congressional Districts

analyses/KY_cd_2020/01_prep_KY_cd_2020.R, analyses/KY_cd_2020/03_sim_KY_cd_2020.R, analyses/KY_cd_2020/doc_KY_cd_2020.md
In Kentucky, under the Criteria and Standards for Congressional Redistricting adopted by Interim Joint Committee on State Government’s Redistricting Subcommittee in 1991, districts must:
5. preserve communities of interest as much as possible
We enforce a maximum population deviation of 0.5%. We use a pseudo-county constraint described below which attempts to mimic the norms in Kentucky of generally preserving county, city, and township boundaries.
Data for Kentucky comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample …
=> 2020 Kentucky Congressional Districts

analyses/WI_cd_2020/02_setup_WI_cd_2020.R, analyses/WI_cd_2020/03_sim_WI_cd_2020.R, analyses/WI_cd_2020/doc_WI_cd_2020.md
In Wisconsin, districts must:
We add a pseudo-county constraint as described below.
Data for Wisconsin comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Wisconsin across 2 independent runs of the SMC algorithm.
We use a pseudo-county constraint to limit the county and municipality splits. Municipality lines are used in Milwaukee County. 
These are larger than the target population for a district. 
```
SMC: 5,000 sampled plans of 8 districts on 7,059 units …
```
=> Re-run 2020 Wisconsin Congressional Districts

analyses/HI_cd_2020/01_prep_HI_cd_2020.R, analyses/HI_cd_2020/03_sim_HI_cd_2020.R, analyses/HI_cd_2020/doc_HI_cd_2020.md
In Hawaii, under [HRS Title 1 S25](https://www.capitol.hawaii.gov/hrscurrent/Vol01_Ch0001-0042F/HRS0025/HRS_0025-0002.htm), districts must:
1. be contiguous unless crossing islands (25-2 (b) (2))
1. be geographically compact (25-2(b)(3))
1. preserve tract boundaries as much as possible (25-2(b)(4))
1. not unduly favor any people or party (25-2(b)(6))
1. avoid mixing substantially different socioeconomic regions (25-2(b)(6))
We use Census tracts are in accordance with (25-2(b)(4)).
We use municipalities to attempt to follow (25-2(b)(6)) in absence of regional knowledge.
Data for Hawaii comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
Islands are connecting in the …
=> Re-run 2020 Hawaii Congressional Districts

analyses/NY_cd_2020/01_prep_NY_cd_2020.R, analyses/NY_cd_2020/03_sim_NY_cd_2020.R, analyses/NY_cd_2020/doc_NY_cd_2020.md
[In New York, districts must](https://www.nysenate.gov/sites/default/files/ckeditor/Oct-21/ny_state_constitution_2021.pdf):
1. be contiguous (III.4(c)(3))
1. have equal populations (III.4(c)(2))
1. be geographically compact (III.4(c)(4))
1. preserve cores of existing districts, political subdivisions, and communities of interest (III.4(c)(5))
1. not be drawn to discourage competition (III.4(c)(5))
1. not be drawn to favor or disfavor incumbents (III.4(c)(5))
1. not be drawn to favor or disfavor parties (III.4(c)(5))
1. not abridge minority group vote power (III.4(c)(1))
We preserve cores of the many geographic regions by using a pseudo county constraint.
Data for New York comes from the ALARM Project's [2020 Redistricting Data …
=> Re-run 2020 New York Congressional Districts

analyses/LA_cd_2020/03_sim_LA_cd_2020.R, analyses/LA_cd_2020/doc_LA_cd_2020.md
In Louisiana, according to [Louisiana Joint Rule No. 21](https://www.legis.la.gov/Legis/Law.aspx?d=1238755) districts must:
4. preserve parish and municipality boundaries as much as possible
5. preserve the cores of traditional district alignments
We enforce a maximum population deviation of 0.5%. We add a hinge Gibbs constraint targeting the same number of majority-minority districts as the enacted plan. We also apply a hinge Gibbs constraint to discourage packing of minority voters.
Data for Louisiana comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
To preserve the cores of prior districts, we merge all precincts which are more than two …
=> Re-run 2020 Louisiana Congressional Districts

analyses/TX_cd_2020/03_sim_TX_cd_2020.R, analyses/TX_cd_2020/04_diagnostics_TX_cd_2020.R, analyses/TX_cd_2020/doc_TX_cd_2020.md
In Texas, districts must meet US constitutional requirements, but there are 
[no state-specific statutes](https://redistricting.capitol.texas.gov/reqs#congress-section).
Data for Texas comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We estimate CVAP populations with the [`cvap`](https://github.com/christopherkenny/cvap)
R package.
We also pre-process the map to split it into clusters for simulation, which has a slight effect on the types of district plans that will be sampled.
We sample 50,000 districting plans for Texas across two independent runs of the SMC algorithm.
Due to the size and complexity of Texas, we split the simulations into
multiple steps.
First, …
=> Re-run 2020 Texas Congressional Districts

analyses/VA_cd_2020/01_prep_VA_cd_2020.R, analyses/VA_cd_2020/03_sim_VA_cd_2020.R, analyses/VA_cd_2020/doc_VA_cd_2020.md
In Virginia, districts must, under Va. Code Ann. § 24.2-304.04:
5. "not, when considered on a statewide basis, unduly favor or disfavor any political party"
Data for Virginia comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 10,000 districting plans for Virginia across two independent runs of the SMC algorithm, and then thin the sample down to 5,000 plans.
To balance county and municipality splits, we create pseudocounties for use in the county constraint, which leads …
=> Re-run 2020 Virginia Congressional Districts

analyses/IL_cd_2020/01_prep_IL_cd_2020.R, analyses/IL_cd_2020/02_setup_IL_cd_2020.R, analyses/IL_cd_2020/03_sim_IL_cd_2020.R, analyses/IL_cd_2020/doc_IL_cd_2020.md
In Illinois, districts must, under Ill. Const. Art. IV, § 3:
Data for Illinois comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 60,000 districting plans for Illinois across two independent runs of the SMC algorithm, and then thin the sample down to 5,000 plans.
To balance county and municipality splits, we create pseudocounties for use in the county constraint, which leads to fewer municipality splits than using a county constraint. These are counties outside of Cook County and DuPage County. Within Cook County and DuPage County, …
=> Rerun 2020 Illinois Congressional Districts

analyses/NC_cd_2020/03_sim_NC_cd_2020.R, analyses/NC_cd_2020/doc_NC_cd_2020.md
In North Carolina, under [North Carolina State Constitution Article II Sections 3 & 5](https://www.ncleg.gov/Laws/Constitution/Article2), districts must:
4. preserve county boundaries as much as possible
We add a hinge Gibbs constraint targeting the same number of majority-minority districts as the enacted plan. We also apply a hinge Gibbs constraint to discourage packing of minority voters.
Data for North Carolina comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/). Data for the 2022 North Carolina ratified congressional map comes from the [North Carolina General …
=> Re-run 2020 North Carolina Congressional Districts

analyses/CA_cd_2020/02_setup_CA_cd_2020.R, analyses/CA_cd_2020/03_sim_CA_cd_2020.R, analyses/CA_cd_2020/doc_CA_cd_2020.md
In California, under [Article XXI](https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=CONS&division=&title=&part=&chapter=&article=XXI), districts must:
1. be contiguous (2d3)
1. have equal populations (2d1) 
1. be geographically compact (2d5)
1. preserve city, county, neighborhood, and community of interest boundaries as much as possible (2d4)
1. not favor or discriminate against incumbents, candidates, or parties (2e)
1. comply with the Voting Rights Act (2d2)
We enforce a maximum population deviation of 0.5%. We add a pseudo-county constraint, as described below. We add VRA constraints encouraging Hispanic VAP and Asian VAP majorities in districts.
Data for California comes from the ALARM Project's [2020 Redistricting Data …
=> Re-run 2020 California Congressional Districts

analyses/NM_cd_2020/01_prep_NM_cd_2020.R, analyses/NM_cd_2020/02_setup_NM_cd_2020.R
In New Mexico, districts must, under [legislation code SB 304](https://www.nmlegis.gov/Legislation/Legislation?Chamber=S&LegType=B&LegNo=304&year=21):
2. be reasonably compact
3. be as equal in population as practicable
4. to the extent feasible, preserve communities of interest and take into consideration political and geographic boundaries
5. to the extent feasible, preserve the core of existing districts
Additionally, race-neutral districting principles shall not be subordinated to racial considerations
We constrain the number of county divisions to 1 less than the number of Congressional Districts.
We perform cores-based simulations, thereby preserving cores of prior districts.
Data for New Mexico comes from the ALARM …
=> 2020 New Mexico Congressional Districts Un-Merge

analyses/MN_cd_2010/01_prep_MN_cd_2010.R, analyses/MN_cd_2010/02_setup_MN_cd_2010.R, analyses/MN_cd_2010/03_sim_MN_cd_2010.R, analyses/MN_cd_2010/doc_MN_cd_2010.md, analyses/SC_cd_2010/03_sim_SC_cd_2010.R
In Minnesota, districts must:
2, have equal populations
3. comply with VRA section 2
4. be geographically compact
5. preserve political subdivisions and communities of interest as possible 
6. avoid pairing incumbents but also cannot give unfair advantage to incumbents (least important criteria)
https://www.mncourts.gov/mncourtsgov/media/CIOMediaLibrary/2011Redistricting/A110152Order11-4-11.pdf
We do not adhere to all criteria in the guidelines. We include the following constraints:
1. We enforce a maximum population deviation of 0.5%. 
2. We use a pseudo-county constraint to help preserve county and municipality boundaries.
Data for Minnesota comes from the ALARM Project's [2010 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
No …
=> # 2010 Minnesota Congressional Districts

analyses/NV_cd_2010/01_prep_NV_cd_2010.R, analyses/NV_cd_2010/02_setup_NV_cd_2010.R, analyses/NV_cd_2010/03_sim_NV_cd_2010.R, analyses/NV_cd_2010/doc_NV_cd_2010.md
In Nevada, districts must (per [judicial order](https://www.ncsl.org/Portals/1/Documents/Redistricting/NV_11-OC-00042-1B_2011-09-21_Order_Re-Redistricting_20076.pdf) for the 2010 cycle):
1.  be contiguous
2.  have equal populations
3.  be geographically compact
4.  preserve county and municipality boundaries as much as possible
5.  preserve communities of interest
6.  avoid pairing incumbents "to the extent practicable"
1.  We enforce a maximum population deviation of 0.5%.
2.  We use a county constraint (with pseudo-counties in Clark County) to preserve communities of interests, municipalities, and counties.
3.  We **do not** include a restriction for avoiding incumbent pairings.
Data for Nevada comes from the ALARM Project's [2010 Redistricting Data …
=> 2010 Nevada Congressional Districts

analyses/NH_cd_2010/01_prep_NH_cd_2010.R, analyses/NH_cd_2010/02_setup_NH_cd_2010.R, analyses/NH_cd_2010/03_sim_NH_cd_2010.R, analyses/NH_cd_2010/doc_NH_cd_2010.md
In New Hampshire, districts must:
Data for New Hampshire comes from the ALARM Project's [2010 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
Since the enacted plan has no minor civil division (MCD) splits, we merge precincts into MCDs prior to simulating districts.
We sample 5,000 districting plans for New Hampshire in 2 independent runs of the sequential Monte Carlo algorithm.
```
SMC: 10,000 sampled plans of 2 districts on 327 units
Plan diversity 80% range: 0.077 to 0.688
R-hat values for summary statistics:
pop_overlap …
```
=> 2010 New Hampshire Congressional Districts

analyses/ME_cd_2010/01_prep_ME_cd_2010.R, analyses/ME_cd_2010/02_setup_ME_cd_2010.R, analyses/ME_cd_2010/03_sim_ME_cd_2010.R, analyses/ME_cd_2010/doc_ME_cd_2010.md
[In Maine, following Title 21-A, Chapter 15, Section 1206, districts must](https://legislature.maine.gov/legis/statutes/21-A/title21-Asec1206.html):
1. be contiguous (1)
1. have equal populations (1)
1. be geographically compact (1)
1. preserve county and municipality boundaries as much as possible (1)
We apply the standard algorithmic county constraint.
Data for Maine comes from the [Voting and Election Science Team](https://dataverse.harvard.edu/dataverse/electionscience) for 2016, 2018, and 2020. It is retabulated to 2020 Census tracts, as 2020 Census VTDs do not cover the majority of Maine's geography.
Islands tracts were connected to the nearest tract within the same district.
We sample 5,000 districting plans for Maine, across 4 …
=> 2010 Maine Congressional Districts

analyses/CT_cd_2010/01_prep_CT_cd_2010.R, analyses/CT_cd_2010/02_setup_CT_cd_2010.R, analyses/CT_cd_2010/03_sim_CT_cd_2010.R, analyses/CT_cd_2010/doc_CT_cd_2010.md, analyses/ME_cd_2020/doc_ME_cd_2020.md
In Connecticut, there are no state law requirements for congressional districts. 
The Supreme Court of Connecticut set out the [following guidelines](https://www.cga.ct.gov/red2011/documents/special_master/Merged%20Draft%20Report%20with%20Exhibits.pdf) in the order appointing a special master.
1. Districts shall be as equal in population as is practicable. 
1. Districts shall be made of contiguous territory. 
1. Districts shall comply with 42 U.S.C. § 1973(b) and with other applicable provisions of the Voting Rights Act and federal law. 
1. Districts shall not be substantially less compact than the existing congressional districts.
1. Districts shall not substantially violate town lines more than the existing congressional districts. 
1. Districts shall not consider either the residency …
=> 2010 Connecticut Congressional Districts

analyses/UT_cd_2010/01_prep_UT_cd_2010.R, analyses/UT_cd_2010/02_setup_UT_cd_2010.R, analyses/UT_cd_2010/03_sim_UT_cd_2010.R, analyses/UT_cd_2010/doc_UT_cd_2010.md
In Utah, there are no state law requirements for congressional districts.
We limit the number of county/municipality splits.
Data for Utah comes from the ALARM Project's [Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Utah across two independent runs of the SMC algorithm.
```
SMC: 5,000 sampled plans of 4 districts on 2,299 units
ℹ Preparing AR shapefile
Plan diversity 80% range: 0.54 to 0.86
ℹ Preparing AR shapefile
R-hat values for summary statistics:
pop_overlap …
```
=> 2010 Utah Congressional Districts

analyses/AR_cd_2010/01_prep_AR_cd_2010.R, analyses/AR_cd_2010/02_setup_AR_cd_2010.R, analyses/AR_cd_2010/03_sim_AR_cd_2010.R, analyses/AR_cd_2010/doc_AR_cd_2010.md
In Arkansas, there are no state law requirements for congressional districts.
We enforce a maximum population deviation of 0.5%, which is in line with the low deviation seen in past congressional district maps.
We limit the number of county/municipality splits, which is in line with the small number of county/municipality splits observed in past congressional district maps.
Data for Arkansas comes from the ALARM Project's [Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Arkansas across two independent runs of the SMC algorithm.
```
SMC: 5,000 sampled plans of 4 districts on 2,784 units …
```
=> 2010 Arkansas Congressional Districts

analyses/MO_cd_2010/01_prep_MO_cd_2010.R, analyses/MO_cd_2010/02_setup_MO_cd_2010.R, analyses/MO_cd_2010/03_sim_MO_cd_2010.R, analyses/MO_cd_2010/doc_MO_cd_2010.md
In Missouri, according to [Mo. Const. art. III, § 2](https://redistricting.lls.edu/wp-content/uploads/MO-2000-constitution.pdf#page=26), districts must:
We enforce a maximum population deviation of 0.5%. We use a standard algorithmic county constraint. We add a hinge Gibbs constraint targeting one majority-minority district to comply with VRA requirements and match the number in the enacted plan.
Data for Missouri comes from the ALARM Project's [Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Missouri across two independent runs of the SMC algorithm.
```
SMC: 5,000 sampled plans of 8 …
```
=> 2010 Missouri Congressional Districts

analyses/WV_cd_2010/01_prep_WV_cd_2010.R, analyses/WV_cd_2010/02_setup_WV_cd_2010.R, analyses/WV_cd_2010/03_sim_WV_cd_2010.R, analyses/WV_cd_2010/doc_WV_cd_2010.md
[In West Virginia, according to [W.V. Const. art. I, § 4](https://www.wvlegislature.gov/WVCODE/Code.cfm?chap=01&art=2), districts must:
1. be made of contiguous counties
We also merge VTDs into counties and run the simulation at the county level.
Data for West Virginia comes from the ALARM Project's [Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for West Virginia across 4 independent runs of the SMC algorithm.
```
SMC: 5,000 sampled plans of 3 districts on 55 units
`adapt_k_thresh`=0.985 • …
```
=> 2010 West Virginia Congressional Districts

analyses/NM_cd_2010/01_prep_NM_cd_2010.R, analyses/NM_cd_2010/02_setup_NM_cd_2010.R, analyses/NM_cd_2010/03_sim_NM_cd_2010.R, analyses/NM_cd_2010/doc_NM_cd_2010.md
In New Mexico, according to the [New Mexico Legislative Council Guidelines](https://www.nmlegis.gov/Redistricting/Documents/187014.pdf), districts must:
5. preserve communities of interest
6. preserve the core of existing districts
We enforce a maximum population deviation of 0.5%. We add a hinge Gibbs constraint targeting the same number of majority-minority districts as the enacted plan. We also apply a hinge Gibbs constraint to discourage packing of minority voters.
Data for New Mexico comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/). Data for the 2010 New Mexico enacted …
=> 2010 New Mexico Congressional Districts

analyses/PA_cd_2010/01_prep_PA_cd_2010.R, analyses/PA_cd_2010/02_setup_PA_cd_2010.R, analyses/PA_cd_2010/03_sim_PA_cd_2010.R, analyses/PA_cd_2010/doc_PA_cd_2010.md
In Pennsylvania, districts must generally:
We use a (pseudo-)county constraint to preserve boundaries as much as possible.
Data for Pennsylvania comes from the ALARM Project's [2010 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 10,000 districting plans for Pennsylvania over two independent runs of the SMC algorithm, and thin the total 20,000 plans down to 5,000. Pseudo-counties for the county constraint are generated for Allegheny, Montgomery, and Philadelphia counties, as they have more residents …
=> 2010 Pennsylvania Congressional Districts

analyses/VA_cd_2010/01_prep_VA_cd_2010.R, analyses/VA_cd_2010/02_setup_VA_cd_2010.R, analyses/VA_cd_2010/03_sim_VA_cd_2010.R, analyses/VA_cd_2010/doc_VA_cd_2010.md
In Virginia, districts must, under [Commitee Resolution No. 1](https://www.virginiaredistricting.org/2010/data/publications/2011Draw1.pdf) adopted by the Senate and House Committees on Privileges and Elections in 2001:
5. preserve communities of interest, as defined by criteria that "may include, among others, economic factors, social factors, cultural factors, geographic features, governmental jurisdictions and service delivery areas, political beliefs, voting trends, and incumbency considerations"
We enforce a maximum population deviation of 0.5%. We use a pseudo-county constraint described below which attempts to mimic the norms in Virginia of …
=> 2010 Virginia Congressional Districts

analyses/MA_cd_2010/01_prep_MA_cd_2010.R, analyses/MA_cd_2010/02_setup_MA_cd_2010.R, analyses/MA_cd_2010/03_sim_MA_cd_2010.R, analyses/MA_cd_2010/doc_MA_cd_2010.md
In Massachusetts, districts must:
1. Be contiguous
2. Have equal populations
3. Be geographically compact
4. Preserve county and municipality boundaries as much as possible
We enforce a maximum population deviation of 0.05%. 
We use a pseudo-county constraint to help preserve county and municipality boundaries.
Data for Massachusetts comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Massachusetts over two runs.
```
SMC: 5,000 sampled plans of 9 districts on 2,165 units
Plan diversity 80% range: …
```
=> 2010 Massachusetts Congressional Districts

analyses/IA_cd_2010/01_prep_IA_cd_2010.R, analyses/IA_cd_2010/02_setup_IA_cd_2010.R, analyses/IA_cd_2010/03_sim_IA_cd_2010.R, analyses/IA_cd_2010/doc_IA_cd_2010.md
In Iowa, districts must:
3. be geographically compact with compactness defined as length-width compactness and perimeter compactness
4. not split counties
5. preserve municipality boundaries as much as possible
We enforce a maximum population deviation of 0.01%.
Data for Iowa comes from the ALARM Project's [2010 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
Shape file was grouped by county to prevent county splits.
We sample 5,000 districting plans for Iowa.
```
SMC: 5,000 sampled plans of 4 districts on 99 units
`adapt_k_thresh`=0.985 • `seq_alpha`=0.9
Plan diversity 80% range: 0.00 to 0.79
R-hat values for …
```
=> 2010 Iowa Congressional Districts

analyses/GA_cd_2010/01_prep_GA_cd_2010.R, analyses/GA_cd_2010/02_setup_GA_cd_2010.R, analyses/GA_cd_2010/03_sim_GA_cd_2010.R, analyses/GA_cd_2010/doc_GA_cd_2010.md, analyses/NJ_cd_2010/01_prep_NJ_cd_2010.R, analyses/NJ_cd_2010/02_setup_NJ_cd_2010.R, analyses/NJ_cd_2010/03_sim_NJ_cd_2010.R, analyses/NJ_cd_2010/doc_NJ_cd_2010.md
In Georgia, under the 2011-12 Guidelines for the House Legislative and Congressional Reapportionment Committee: districts must:
4. preserve political subdivisions and communities of interest 
5. avoid pairing incumbents 
[Guidelines for the House Legislative and Congressional Reapportionment Committee](https://www.dropbox.com/s/i8zqyivtr8iozs8/GeorgiaSenateCommitteeGuidelines2011-12.pdf)
Data for Georgia comes from the ALARM Project's [2010 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 60,000 districting plans for Georgia across two independent runs of the SMC …
=> 2010 Georgia Congressional Districts

analyses/NJ_cd_2010/01_prep_NJ_cd_2010.R, analyses/NJ_cd_2010/02_setup_NJ_cd_2010.R, analyses/NJ_cd_2010/03_sim_NJ_cd_2010.R, analyses/NJ_cd_2010/doc_NJ_cd_2010.md
In New Jersey, districts must:
We use a pseudo-county constraint described below which attempts to mimic the norms in New Jersey of generally preserving county and municipal boundaries.
Data for New Jersey comes from the ALARM Project's [2010 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 10,000 districting plans for New Jersey across two independent runs of the SMC algorithm, and then thin the sample to down to 5,000 plans. To balance county and municipality splits, we create pseudocounties for use in the county constraint. These are counties, outside of Bergen, Burlington, Camden, Essex, …
=> 2010 New Jersey Congressional Districts

analyses/AZ_cd_2010/01_prep_AZ_cd_2010.R, analyses/AZ_cd_2010/02_setup_AZ_cd_2010.R, analyses/AZ_cd_2010/03_sim_AZ_cd_2010.R, analyses/AZ_cd_2010/doc_AZ_cd_2010.md
In Arizona, districts must:
1. favor competitive districts to the extent practicable
We add a county/municipality constraint, as described below.
We add a hinge Gibbs constraint targeting two majority-HVAP districts, one within Maricopa County and one outside of it (as exist in the enacted plan.) However, not all plans are guaranteed to have two majority-HVAP districts.
Data for Arizona comes from the ALARM Project's [Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 32,000 districting plans for Arizona …
=> 2010 Arizona Congressional Districts

analyses/KS_cd_2010/01_prep_KS_cd_2010.R, analyses/KS_cd_2010/02_setup_KS_cd_2010.R, analyses/KS_cd_2010/03_sim_KS_cd_2010.R, analyses/KS_cd_2010/doc_KS_cd_2010.md
In Kansas, under the [Guidelines And Criteria For 2012 Kansas Congressional And Legislative Redistricting](http://www.kslegislature.org/li_2012/b2011_12/committees/misc/ctte_h_redist_1_20120109_01_other.pdf) districts must:
1. be contiguous (5)
1. have equal populations (2)
1. be geographically compact (5)
1. preserve county and municipality boundaries as much as possible (4c)
1. preserve communities of interest (4a)
1. preserve cores of existing districts (4b)
1. be built primarily from counties and VTDs (1)
Data for Kansas comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
To preserve the cores of prior districts, we merge all precincts which are more than two …
=> 2010 Kansas Congressional Districts

analyses/AL_cd_2010/01_prep_AL_cd_2010.R, analyses/AL_cd_2010/02_setup_AL_cd_2010.R, analyses/AL_cd_2010/03_sim_AL_cd_2010.R, analyses/AL_cd_2010/doc_AL_cd_2010.md
In Alabama, districts must:
5. preserve communities of interest as much as possible
We enforce a maximum population deviation of 0.5%. We add a hinge Gibbs constraint targeting the same number of majority-minority districts as the enacted plan.
Data for Alabama comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/). Data for the 2010 Alabama enacted congressional map comes from [All About Redistricting](https://redistricting.lls.edu/state/alabama/?cycle=2020&level=Congress&startdate=2021-11-04).
We sample 20,000 districting plans for …
=> 2010 Alabama Congressional Districts

analyses/LA_cd_2010/01_prep_LA_cd_2010.R, analyses/LA_cd_2010/02_setup_LA_cd_2010.R, analyses/LA_cd_2010/03_sim_LA_cd_2010.R, analyses/LA_cd_2010/doc_LA_cd_2010.md
In Louisiana, according to [La. Const. art. III, § 6](https://senate.la.gov/Documents/Constitution/Article3.htm#%C2%A76%20Legislative%20Reapportionment;%20Reapportionment%20by%20Supreme%20Court;%20Procedure), districts must:
4. preserve parish and municipality boundaries as much as possible
5. preserve the cores of traditional district alignments
We enforce a maximum population deviation of 0.5%. We add a hinge Gibbs constraint targeting the same number of majority-minority districts as the enacted plan. We also apply a hinge Gibbs constraint to discourage packing of minority voters.
Data for Louisiana comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census- …
=> 2010 Louisiana Congressional Districts

analyses/WI_cd_2010/01_prep_WI_cd_2010.R, analyses/WI_cd_2010/02_setup_WI_cd_2010.R, analyses/WI_cd_2010/03_sim_WI_cd_2010.R, analyses/WI_cd_2010/doc_WI_cd_2010.md
In Wisconsin, districts must:
We enforce a maximum population deviation of 0.5% and add a pseudo-county constraint to reduce county and municipality splits. Since Milwaukee County has a greater population than the target district population, we split Milwaukee County by municipality lines.
Data for Wisconsin comes from the ALARM Project's [2010 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 10,000 districting plans for Wisconsin over 2 independent runs of the SMC algorithm.
```
SMC: 10,000 sampled plans of 8 districts on 6,290 units
`est_label_mult`=1 • …
```
=> 2010 Wisconsin Congressional Districts

analyses/OH_cd_2010/01_prep_OH_cd_2010.R, analyses/OH_cd_2010/02_setup_OH_cd_2010.R, analyses/OH_cd_2010/03_sim_OH_cd_2010.R, analyses/OH_cd_2010/doc_OH_cd_2010.md
In Ohio, districts must:
4. preserve political subdivisions
We enforce a maximum population deviation of 0.05%. We use a pseudo-county constraint to help preserve county and municipality boundaries. See '02_setup_OH_cd_2010.R' file.
Data for Ohio comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 13,000 districting plans for Massachusetts over two runs. We then thinned the number of samples to 5,000. No special techniques were needed to produce the sample.
```
SMC: 5,000 sampled plans of 16 districts on 11,029 units
`est_label_mult`=1 • …
```
=> 2010 Ohio Congressional Districts

analyses/RI_cd_2010/01_prep_RI_cd_2010.R, analyses/RI_cd_2010/02_setup_RI_cd_2010.R, analyses/RI_cd_2010/03_sim_RI_cd_2010.R
Hi @mzhao80, just gave a quick look over it. I think the issue came from using blocks, whereas it should be a tract-level analysis since there are no vtds. I made the necessary changes and also updated `sd` -> `ssd` so it's consistent with variable names that we've used in the broader ALARM Project naming schemes.
Feel free to merge or just pull out the pieces that are helpful to you.
=> tract change + use `ssd` for project-wide consistency

analyses/WA_cd_2010/01_prep_WA_cd_2010.R, analyses/WA_cd_2010/02_setup_WA_cd_2010.R, analyses/WA_cd_2010/03_sim_WA_cd_2010.R, analyses/WA_cd_2010/doc_WA_cd_2010.md
In Washington, districts must according to HCR 4409 (https://apps.leg.wa.gov/billsummary/?BillNumber=4409&Year=2011&Initiative=false):
We enforce a maximum population deviation of 0.5%. We also used ferry routes in order to create districts linking precincts that are offshore. 
Data for Washington comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
As described above, the adjacency graph was modified by hand to reflect Washington's contiguity requirements. The full list of these changes can be found in the '01_prep_WA_cd_2010.R' file.
We sample 13,000 districting plans for …
=>  2010 Washington Congressional Districts

analyses/TX_cd_2010/01_prep_TX_cd_2010.R, analyses/TX_cd_2010/02_setup_TX_cd_2010.R, analyses/TX_cd_2010/03_sim_TX_cd_2010.R, analyses/TX_cd_2010/04_diagnostics_TX_cd_2010.R, analyses/TX_cd_2010/doc_TX_cd_2010.md
In Texas, districts must meet US constitutional requirements, but there are
[no state-specific statutes](https://redistricting.capitol.texas.gov/pdf/Guide_to_2011_Redistricting.pdf).
Data for Texas comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We estimate CVAP populations with the `cvap` R package.
We also pre-process the map to split it into clusters for simulation, which has a slight effect on the types of district plans that will be sampled.
We sample 50,000 districting plans for Texas across two independent runs of the SMC algorithm, and then thin the sample to down to 5,000 plans. We use a pseudo-county constraint to limit the county and municipality …
=> 2010 Texas Congressional Districts

analyses/KY_cd_2010/01_prep_KY_cd_2010.R, analyses/KY_cd_2010/02_setup_KY_cd_2010.R, analyses/KY_cd_2010/03_sim_KY_cd_2010.R, analyses/KY_cd_2010/doc_KY_cd_2010.md, analyses/KY_cd_2020/03_sim_KY_cd_2020.R
In Kentucky, under the [Criteria and Standards for Congressional Redistricting](https://web.archive.org/web/20220101204327/http://ncsl.org/Portals/1/Documents/Redistricting/Redistricting_2010.pdf) adopted by Interim Joint Committee on State Government’s Redistricting Subcommittee in 1991, districts must:
5. preserve communities of interest as much as possible
We enforce a maximum population deviation of 0.5%. We use a pseudo-county constraint described below which attempts to mimic the norms in Kentucky of generally preserving county, city, and township boundaries.
Data for Kentucky comes from the ALARM Project's [2020 Redistricting Data …
=> 2010 Kentucky Congressional Districts

analyses/OR_cd_2010/01_prep_OR_cd_2010.R, analyses/OR_cd_2010/02_setup_OR_cd_2010.R, analyses/OR_cd_2010/03_sim_OR_cd_2010.R, analyses/OR_cd_2010/doc_OR_cd_2010.md
In Oregon, according to [Or. Rev. Stat. § 188.010](https://www.oregonlegislature.gov/bills_laws/archive/2011ors188.pdf) of the state constitution, districts must:
4. be connected by transportation links
5. preserve county and municipality boundaries as much as possible
We enforce a maximum population deviation of 0.5%. We use a pseudo-county constraint to help preserve county and municipality boundaries, as described below.
Data for Oregon comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
Oregon does not submit precinct boundaries to the Census Bureau. The base shapefile consists of tracts, but where tracts are split by the enacted …
=> Oregon 2010 Congressional Districts 

analyses/RI_cd_2010/01_prep_RI_cd_2010.R, analyses/RI_cd_2010/02_setup_RI_cd_2010.R, analyses/RI_cd_2010/03_sim_RI_cd_2010.R, analyses/RI_cd_2010/doc_RI_cd_2010.md
In Rhode Island, according to [Chapter 106, Section 2 of the 2011 Rhode Island Laws](http://webserver.rilin.state.ri.us/PublicLaws/law11/law11106.htm), districts must:
1. preserve state senate districts as much as possible
Data for Rhode Island comes from the ALARM Project's [Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 5,000 districting plans for Rhode Island across four independent runs of the SMC algorithm.
We assign state senate districts to act like counties so that the simulations minimize the number of state senate district splits.
```
SMC: 5,000 sampled …
```
=> 2010 Rhode Island Congressional Districts

analyses/ID_cd_2010/01_prep_ID_cd_2010.R, analyses/ID_cd_2010/02_setup_ID_cd_2010.R, analyses/ID_cd_2010/03_sim_ID_cd_2010.R, analyses/ID_cd_2010/doc_ID_cd_2010.md
[In Idaho, districts must:](https://legislature.idaho.gov/statutesrules/idstat/Title72/T72CH15/SECT72-1506/)
1. be contiguous (72-1506(6)).
2. have equal populations (72-1506(3)).
3. be geographically compact (72-1506(4), 72-1506(5)).
4. preserve county and municipality boundaries as much as possible (72-1506(2)).
5. not be drawn to favor party or incumbents (72-1506(8)).
6. connect counties based on highways (72-1506(9)).
Data for Idaho comes from the [Loyala Law School (LLS) All About Redistricting](https://redistricting.lls.edu/state/idaho/?cycle=2010&level=Congress&startdate=2011-10-17) project
We sample 15,000 districting plans for Idaho, across 2 independent runs of the SMC …
=> 2010 Idaho Congressional Districts

analyses/CA_cd_2010/01_prep_CA_cd_2010.R, analyses/CA_cd_2010/02_setup_CA_cd_2010.R, analyses/CA_cd_2010/03_sim_CA_cd_2010.R, analyses/CA_cd_2010/doc_CA_cd_2010.md
In California, according to the [California Constitution Article XXI](https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=CONS&division=&title=&part=&chapter=&article=XXI), districts must:
4. preserve city, county, neighborhood, and community of interest boundaries as much as possible
5. not favor or discriminate against incumbents, candidates, or parties
6. comply with the federal Voting Rights Act
We enforce a maximum population deviation of 0.5%. We use a pseudo-county constraint to limit the county and municipality splits. We add VRA constraints encouraging Hispanic VAP and Asian VAP majorities in districts.
Data for California comes from the ALARM Project's [2020 Redistricting Data …
=> 2010 California Congressional Districts

analyses/MI_cd_2010/01_prep_MI_cd_2010.R, analyses/MI_cd_2010/02_setup_MI_cd_2010.R, analyses/MI_cd_2010/03_sim_MI_cd_2010.R, analyses/MI_cd_2010/doc_MI_cd_2010.md
in Michigan, according to (http://www.legislature.mi.gov/(S(xxvumgge0jwzkeswmwt0bh4v))/mileg.aspx?page=GetObject&objectname=mcl-Article-IV-6), districts must:
5. cannot favor/disfavor incumbents
We enforce a maximum population deviation of 0.5%. We applied a constraint to limit county and municipality splits (see '02_setup_MI_cd_2010.R' file).
Data for Michigan comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/).
We sample 8,000 districting plans for Michigan across two independent runs of the SMC algorithm and then thinned our …
=> 2010 Michigan Congressional Districts

analyses/HI_cd_2010/03_sim_HI_cd_2010.R, analyses/NH_cd_2010/03_sim_NH_cd_2010.R, analyses/NV_cd_2010/03_sim_NV_cd_2010.R, analyses/NY_cd_2010/03_sim_NY_cd_2010.R, analyses/WI_cd_2010/03_sim_WI_cd_2010.R
Updated Nevada, New Hampshire, and Wisconsin to thin existing plans (generated 5,000 over 2 runs for 10,000 total) to 5,000 for all.
Updated New York to ensure the thinned plans are saved.
Updated Hawaii to match district numbering to the reference enacted plan.
@christopherkenny
=> Thin NV, NH, and WI, save thinned plans in NY, and update HI numbering

analyses/KS_cd_2020/01_prep_KS_cd_2020.R, analyses/KS_cd_2020/02_setup_KS_cd_2020.R, analyses/KS_cd_2020/03_sim_KS_cd_2020.R
In Kansas, according to the [Proposed Guidelines and Criteria for 2022 Kansas Congressional Redistricting](https://redistricting.lls.edu/wp-content/uploads/KS-Proposed-redistricting-guidelines.pdf) districts must:
5. preserve the cores of existing districts
6. preserve communities of social, cultural, racial, ethnic, and economic interest to the extent possible
We enforce a maximum population deviation of 0.5%. We add a county constraint.
Data for Kansas comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/). Data for the 2022 Kansas enacted congressional map comes from the [American …
=> 2020 Kansas Congressional Districts (Fixes cores)

analyses/OR_cd_2020/01_prep_OR_cd_2020.R, analyses/OR_cd_2020/03_sim_OR_cd_2020.R, analyses/OR_cd_2020/doc_OR_cd_2020.md
In Oregon, districts must, under Or. Rev. Stat. § 188.010:
1. be of equal population
1. utilize existing geographic or political boundaries
1. not divide communities of common interest
1. be connected by transportation links
Additionally, districts may not favor any political party or incumbent, and may not dilute the voting strength of any language or ethnic minority group.
To reflect the transportation links constraint, we remove edges in the adjacency graph for counties not connected by a state or federal highway.
Data for Oregon comes from the ALARM Project's [2020 Redistricting Data Files](https://alarm-redist.github.io/posts/2021-08-10-census-2020/). …
=> 2020 Oregon Congressional Districts (removes split tracts)

analyses/HI_cd_2010/01_prep_HI_cd_2010.R, analyses/HI_cd_2010/02_setup_HI_cd_2010.R, analyses/HI_cd_2010/03_sim_HI_cd_2010.R, analyses/HI_cd_2010/doc_HI_cd_2010.md
Per Hawaii Revised Statutes 25-2(b)(1)-(4) and (6), [as in force for the 2010 cycle](https://www.ncsl.org/Portals/1/Documents/Redistricting/Redistricting_2010.pdf), districts must:
1\. not unduly favor any person or party;
2\. be contiguous, except when encompassing more than one island;
3\. be compact;
4\. where possible, follow geographical and recognized features and coincide with tract boundaries;
6\. where practicable, avoid mixing regions with different socioeconomic interests.
We enforce a maximum population deviation of 0.5%. We use Census tracts in line with 25-2(b)(4). In absence of regional knowledge about features and socioeconomic interests, we use municipalities to attempt to enforce 25-2(b)(4) and (6).
Data for Hawaii comes from the ALARM Project's [2010 Redistricting Data …
=> 2010 Hawaii Congressional Districts (use VTD not tract)

analyses/NV_cd_2000/01_prep_2000_NV_cd_2000.R, analyses/NV_cd_2000/02_setup_NV_cd_2000.R, analyses/NV_cd_2000/03_sim_NV_cd_2000.R, analyses/NV_cd_2000/doc_NV_cd_2000.md
In Nevada, districts must:
Data for Nevada comes from the [ALARM Project's update](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZV5KF3) to [The Record of American Democracy](https://road.hmdc.harvard.edu/).
We sample 5,000 districting plans for Nevada.
```
SMC: 5,000 sampled plans of 3 districts on 1,291 units
`adapt_k_thresh`=0.99 • `seq_alpha`=0.5
`pop_temper`=0
Plan diversity 80% range: 0.42 to 0.61
R-hat values for summary statistics:
pop_overlap   total_vap …
```
=> 2000 Nevada Congressional Districts

analyses/HI_cd_2000/01_prep_HI_cd_2000.R, analyses/HI_cd_2000/02_setup_HI_cd_2000.R, analyses/HI_cd_2000/03_sim_HI_cd_2000.R, analyses/HI_cd_2000/doc_HI_cd_2000.md
In Hawaii, according to [NCSL Redistricting Law 2000](https://web.archive.org/web/20041216185957/https://www.senate.mn/departments/scr/redist/red2000/Tab5appx.htm), districts:
1\. shall not extend beyond the boundaries of any basic island unit.
2\. shall not be so drawn as to unduly favor a person or political faction.
3\. shall be contiguous, except in the case of districts encompassing more than one island, districts.
4\. shall be compact.
5\. shall follow permanent and easily recognized features, such as streets, streams and clear geographical features, and, when practicable, shall coincide with census tract boundaries.
8\. Where practicable, submergence of an area in a larger district wherein substantially different socio-economic interests predominate shall be avoided.
We enforce a …
=> 2000 Hawaii Congressional Districts

analyses/CO_cd_2000/01_prep_2000_CO_cd_2000.R, analyses/CO_cd_2000/02_setup_CO_cd_2000.R, analyses/CO_cd_2000/03_sim_CO_cd_2000.R, analyses/CO_cd_2000/doc_CO_cd_2000.md
In Colorado, according to [NCSL Redistricting Law 2000](https://web.archive.org/web/20041216185957/https://www.senate.mn/departments/scr/redist/red2000/Tab5appx.htm), districts must:
1. follow the Voting Rights Act
Data for Colorado comes from the [ALARM Project's update](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZV5KF3) to [The Record of American Democracy](https://road.hmdc.harvard.edu/).
We sample 10,000 districting plans for Colorado across 5 independent runs of the SMC algorithm.
We then thinned the number of samples …
=> 2000 Colorado Congressional Districts

analyses/KY_cd_2000/01_prep_2000_KY_cd_2000.R, analyses/KY_cd_2000/02_setup_KY_cd_2000.R, analyses/KY_cd_2000/03_sim_KY_cd_2000.R, analyses/KY_cd_2000/doc_KY_cd_2000.md
In Kentucky, according to [NCSL Redistricting Law 2000](https://web.archive.org/web/20041216185957/https://www.senate.mn/departments/scr/redist/red2000/Tab5appx.htm), districts must:
1. meet the requirements of Section 2 of the Voting Rights Act
1. preserve communities of interest
1. preserve cores of existing districts
Data for Kentucky comes from the [ALARM Project's update](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZV5KF3) to [The Record of American Democracy](https://road.hmdc.harvard.edu/).
To preserve the cores of prior districts, we merge all precincts which are …
=> 2000 Kentucky Congressional Districts

analyses/KS_cd_2000/01_prep_2000_KS_cd_2000.R, analyses/KS_cd_2000/02_setup_KS_cd_2000.R, analyses/KS_cd_2000/03_sim_KS_cd_2000.R, analyses/KS_cd_2000/doc_KS_cd_2000.md
In Kansas, according to [NCSL Redistricting Law 2000](https://web.archive.org/web/20041216185957/https://www.senate.mn/departments/scr/redist/red2000/Tab5appx.htm), districts must:
1. preserve communities of interest
1. not be drawn to dilute minority voting strength or protect or defeat an incumbent
Data for Kansas comes from the [ALARM Project's update](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZV5KF3) to [The Record of American Democracy](https://road.hmdc.harvard.edu/).
We sample 10,000 districting plans for Kansas …
=> 2000 Kansas Congressional Districts

analyses/WV_cd_2000/01_prep_WV_cd_2000.R, analyses/WV_cd_2000/02_setup_WV_cd_2000.R, analyses/WV_cd_2000/03_sim_WV_cd_2000.R, analyses/WV_cd_2000/doc_WV_cd_2000.md
In ``West Virginia``, according to [NCSL Redistricting Law 2000](https://web.archive.org/web/20041216185957/https://www.senate.mn/departments/scr/redist/red2000/Tab5appx.htm), districts shall:
1. be made of contiguous counties
We also merge VTDs into counties and run the simulation at the county level.
Data for ``West Virginia`` comes from the [ALARM Project's update](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZV5KF3) to [The Record of American Democracy](https://road.hmdc.harvard.edu/).
We sample 10,000 districting plans for ``West Virginia`` across 5 independent runs of the SMC algorithm.
We then …
=> 2000 West Virginia Congressional Districts
